In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline


In [2]:
dataset1= pd.read_csv(r'C:\Users\Sara\Desktop\csv files for project\combination_response_3_datasets\Combo_1.csv',encoding="latin1")
dataset1.head()
common=pd.read_csv(r'C:\Users\Sara\PycharmProjects\Adoption_survey\common.csv',encoding="latin1")

In [3]:
# for 'common' columns 
dataset1 = dataset1[['COM1','COM2','COM3','COM4','COM5','COM6','COM7','COM8','COM9','COM10','COM11','COM12','COM13','COM14','COM15','COM_Label']]
X = dataset1.drop('COM_Label', axis=1)
y = dataset1['COM_Label']

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

In [5]:
from sklearn.tree import DecisionTreeClassifier
classifier1 = DecisionTreeClassifier()
classifier1.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [6]:
y_pred = classifier1.predict(common)
print(y_pred)

[1]


In [21]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[376  19]
 [ 11 370]]
              precision    recall  f1-score   support

           0       0.97      0.95      0.96       395
           1       0.95      0.97      0.96       381

    accuracy                           0.96       776
   macro avg       0.96      0.96      0.96       776
weighted avg       0.96      0.96      0.96       776



In [18]:
from sklearn.metrics import accuracy_score
print('Accuracy score:',accuracy_score(y_test, y_pred))

Accuracy score: 0.9445876288659794


In [7]:
from sklearn.externals import joblib
import warnings
with warnings.catch_warnings():
    # filter sklearn\externals\joblib\parallel.py:268:
    # DeprecationWarning: check_pickle is deprecated
    warnings.simplefilter("ignore", category=DeprecationWarning)
    

pkl_file = r"C:\Users\Sara\PycharmProjects\Adoption_survey\venv\saved_model1.pkl"
file = open(pkl_file,"wb")
joblib.dump(classifier1, file)
file.close()

C:\Users\Sara\AppData\Local\Programs\Python\Python36-32\lib\site-packages\sklearn\externals\joblib\__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)


In [8]:
dataset2= pd.read_csv(r'C:\Users\Sara\Desktop\csv files for project\combination_response_3_datasets\Combo_2.csv',encoding="latin1")
dataset2.head()
child=pd.read_csv(r'C:\Users\Sara\PycharmProjects\Adoption_survey\child.csv',encoding="latin1")

In [9]:
# for 'child' columns 
dataset2 = dataset2[['CHI1','CHI2','CHI3','CHI4','CHI5','CHI6','CHI_Label']]
X = dataset2.drop('CHI_Label', axis=1)
y = dataset2['CHI_Label']

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

In [11]:
from sklearn.tree import DecisionTreeClassifier
classifier2 = DecisionTreeClassifier()
classifier2.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [12]:
y_pred = classifier2.predict(child)
print(y_pred)


[0]


In [30]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[24  1]
 [ 2 15]]
              precision    recall  f1-score   support

           0       0.92      0.96      0.94        25
           1       0.94      0.88      0.91        17

    accuracy                           0.93        42
   macro avg       0.93      0.92      0.93        42
weighted avg       0.93      0.93      0.93        42



In [31]:
from sklearn.metrics import accuracy_score
print('Accuracy score:',accuracy_score(y_test, y_pred))

Accuracy score: 0.9285714285714286


In [13]:
from sklearn.externals import joblib

pkl_file = r"C:\Users\Sara\PycharmProjects\Adoption_survey\venv\saved_model2.pkl"
file = open(pkl_file,"wb")
joblib.dump(classifier2, file)
file.close()

In [14]:
dataset3= pd.read_csv(r'C:\Users\Sara\Desktop\csv files for project\combination_response_3_datasets\Combo_3.csv',encoding="latin1")
dataset3.head()
adolescent=pd.read_csv(r'C:\Users\Sara\PycharmProjects\Adoption_survey\adolescent.csv',encoding="latin1")

In [15]:
# for 'adolescent' columns 
adolescent=pd.read_csv(r'C:\Users\Sara\PycharmProjects\Adoption_survey\adolescent.csv',encoding="latin1")
dataset3 = dataset3[['ADU1','ADU2','ADU3','ADU4','ADU5','ADU6','ADU7','ADU8','ADU_Label']]
X = dataset3.drop('ADU_Label', axis=1)
y = dataset3['ADU_Label']

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

In [17]:
from sklearn.tree import DecisionTreeClassifier
classifier3 = DecisionTreeClassifier()
classifier3.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [18]:
y_pred = classifier3.predict(adolescent)
print(y_pred)

[0]


In [75]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[48  2]
 [ 6 43]]
              precision    recall  f1-score   support

           0       0.89      0.96      0.92        50
           1       0.96      0.88      0.91        49

    accuracy                           0.92        99
   macro avg       0.92      0.92      0.92        99
weighted avg       0.92      0.92      0.92        99



In [40]:
from sklearn.metrics import accuracy_score
print('Accuracy score:',accuracy_score(y_test, y_pred))

Accuracy score: 0.9292929292929293


In [19]:
from sklearn.externals import joblib

pkl_file = r"C:\Users\Sara\PycharmProjects\Adoption_survey\venv\saved_model3.pkl"
file = open(pkl_file,"wb")
joblib.dump(classifier3, file)
file.close()